language: node_js
node_js:
  - lts/*

cache: npm

script:
  - npm run build
  - cp dist/index.html dist/404.html

deploy:
  provider: pages
  fqdn: beta.nutbox.io
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master
